NUM_py

In [17]:
import numpy as np

In [29]:
import numpy as np

a = np.array([1, 3, 9, 0, 'hello'])
print()

In [30]:
import numpy as np
np_arr = np.array([3, 3, 3, 3, 3, 3, 'hello', False])
print(np_arr)
# print(bool(np_arr[-1]))
# a = False
# print(bool(a))


['3' '3' '3' '3' '3' '3' 'hello' 'False']


In [32]:
a='sagar'
print(bool(a))

True


In [34]:
a='0'
print(bool(a))


True


In [46]:
a=np.zeros((2,3,4),dtype=int)

print(a)
print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [49]:
import numpy as np

a = np.empty((2, 3, 4), dtype=int)

print(a)
# print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [50]:
a=np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [59]:
a=np.arange(2,8,4) #starrt ho raha hai 4 se
print(a)

[2 6]


In [61]:
a=np.linspace(2,8,4,dtype=int)
print(a)

[2 4 6 8]


Array inspection

In [65]:
import numpy as np

a = np.array([2, 3, 4, 5, 6])

print(np.shape(a))
print(np.size(a))
print(a)

(5,)
5
[2 3 4 5 6]


In [70]:
a=np.arange(2,12,4)
# a=np.zeros(2,12,4)
print(a.shape,a.size)

(3,) 3


BRODCST

In [85]:
import numpy as np

a = np.random.randint(2, 8, 7) #random value print 2 start point, 8 end point ,size=7
print(a)

[3 6 3 7 6 4 3]


In [78]:
import numpy as np

a = np.random.choice([2, 8], 7) #random value print 2 start point, 8 end point ,size=7
print(a)

[8 2 8 2 8 2 8]


In [94]:
a=np.array([2,6,8,7])
b=np.array([3,4,3,7])
print(a*2)
print(a+b)
print(a/b)
print(a-b)



[ 4 12 16 14]
[ 5 10 11 14]
[0.66666667 1.5        2.66666667 1.        ]
[-1  2  5  0]


In [122]:
a = [2, 6, 8, 7]
b = [3, 4, 3, 7]

print(a * 2)
print(a + b)
print(a - b)



[2, 6, 8, 7, 2, 6, 8, 7]
[2, 6, 8, 7, 3, 4, 3, 7]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [112]:
a=np.random.randint(2,15,6)
print(a)

b=a.reshape((3,2))
print(b)


[ 5  9 11 14 14  6]
[[ 5  9]
 [11 14]
 [14  6]]


concatenate

In [117]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
concat=np.concatenate((a,b))
print(concat)

[2 3 5 7 3 6 8 2]


transpose

In [119]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
trans=np.transpose((a,b))
print(trans)

[[2 3]
 [3 6]
 [5 8]
 [7 2]]


where function

In [129]:
a=np.random.randint([2,15,6])
b=np.random.randint([1,19,6])
print(a)
print(b)
c=np.where(b>2,b,a)
print(c)

[0 5 2]
[ 0 18  2]
[ 0 18  2]


sort

In [131]:
a=np.array([2,8,5,7])
b=np.array([3,6,8,2])
sort=np.sort((a,b))
print(sort)

[[2 5 7 8]
 [2 3 6 8]]


std

In [132]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
std=np.std((a,b))
print(std)

2.179449471770337


mean

In [133]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
mean=np.mean((a,b))
print(mean)

4.5


min

In [134]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
min=np.min((a,b))
print(min)

2


unique

In [135]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
unique=np.unique((a,b))
print(unique)

[2 3 5 6 7 8]


matmul

In [136]:
a=np.array([2,3,5,7])
b=np.array([3,6,8,2])
matmul=np.matmul((a,b))
print(matmul)

TypeError: matmul() takes from 2 to 3 positional arguments but 1 were given

QUESTION

In [146]:
lst = []
for i in range(1,8):
    print("Day",i, ":")
    lst.append(int(input()))

import numpy as np
a = np.array(lst)
print(a)


print("min:",np.min(a))
print("max:",np.max(a))
print("avg:",np.mean(a))
print("meadian:",np.median(a))
print("standard deviation:",np.std(a))



Day 1 :
40
Day 2 :
50
Day 3 :
20
Day 4 :
309
Day 5 :
349
Day 6 :
34
Day 7 :
43
[ 40  50  20 309 349  34  43]
min: 20
max: 349
avg: 120.71428571428571
meadian: 43.0
standard deviation: 132.44051417869974


In [ ]:
score=[]
days=['mon','tue','wed']
for i in range(7)
x=input()

In [ ]:
score=input().split()
print(score)
score=[int(x)for x in]