In [ ]:
weekly_sales = {}

n = int(input("How many items? "))

for i in range(n):
    item = input("Enter item name: ")
    quantity = int(input("Enter quantity sold: "))

    weekly_sales[item] = quantity

print("\nWeekly Sales Summary")

for item in weekly_sales:
    print(item, ":", weekly_sales[item])

#create a 5*5 matrix of random integer (1-90)
#find mean of value row and column wise
#replace all even no with -1
#sort the array row and column wise
#find row and column wise seperetly
#count the no of -ve in each column



In [16]:
import numpy as np
arr=np.random.randint(1,91,(5,5))
print("\n matrix")

print(arr)

row_mean=np.mean(arr,axis=1)
col_mean=np.mean(arr,axis=0)
print("\n row wise mean")

print(row_mean)
print("\n col wise mean")
print(col_mean)

arr[arr%2==0]=-1
print("\n even")
print(arr)

row_sorted=np.sort(arr,axis=1)
print("\n row wise sprted")
print(row_sorted)

col_sorted=np.sort(arr,axis=0)
print("\n col wise sprted")
print(col_sorted)

row_sum=np.sum(arr,axis=1)
print("\n row wise sum")
print(row_sum)

col_sum=np.sum(arr,axis=1)
print("\n col wise sum")
print(col_sum)

negative_count=np.sum(arr<0,axis=0)
print("\n negative")
print(negative_count)





 matrix
[[68  3 13 36  2]
 [79 52 84 28 76]
 [32 69 52 22 18]
 [77 80 56 49 78]
 [60 38 90 59 64]]

 row wise mean
[24.4 63.8 38.6 68.  62.2]

 col wise mean
[63.2 48.4 59.  38.8 47.6]

 even
[[-1  3 13 -1 -1]
 [79 -1 -1 -1 -1]
 [-1 69 -1 -1 -1]
 [77 -1 -1 49 -1]
 [-1 -1 -1 59 -1]]

 row wise sprted
[[-1 -1 -1  3 13]
 [-1 -1 -1 -1 79]
 [-1 -1 -1 -1 69]
 [-1 -1 -1 49 77]
 [-1 -1 -1 -1 59]]

 col wise sprted
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [77  3 -1 49 -1]
 [79 69 13 59 -1]]

 row wise sum
[ 13  75  65 123  55]

 col wise sum
[ 13  75  65 123  55]

 negative
[3 3 4 3 5]


question-2

#inventry constrol system


#task:

#create a 5*5 array(stock level)
#create another 5*5 array(demand)
#compute:
#remaining stock=stock-demand
#replace
#  negative value->0(out of stock)
#find:
#total shortage
#product with zero stock
#sort each row based on remaing stock

In [28]:
import numpy as np
create_stock=np.random.randint(20,81,(5,5))
print("\n create stock")
print(create_stock)

create_stock_demand=np.random.randint(20,81,(5,5))
print("\n create stock_demand")
print(create_stock_demand)


print("\n remaing stock")
print(create_stock - create_stock_demand)

print("\n out of strock")
out_ofstock=np.where(create_stock-create_stock_demand<0,0,create_stock-create_stock_demand)
print(out_ofstock)

print("\n total sortage")
total_sortage=np.sum(np.where(create_stock-create_stock_demand<0,1,0),axis=0)
print(total_sortage)

# products with zero stock
zero_stock=np.sum(np.where(create_stock-create_stock_demand==0,1,0),axis=0)
print("\n products with zero stock")
print(zero_stock)

# sort each row based on remaining stock
print("\n sort each row based on remaining stock")
print(np.sort(out_ofstock,axis=1))








 create stock
[[50 60 63 23 77]
 [62 53 48 69 71]
 [76 38 58 43 60]
 [74 24 48 20 66]
 [29 36 43 38 41]]

 create stock_demand
[[48 23 75 40 79]
 [66 56 71 20 43]
 [22 53 68 32 80]
 [31 53 29 26 77]
 [49 46 38 31 73]]

 remaing stock
[[  2  37 -12 -17  -2]
 [ -4  -3 -23  49  28]
 [ 54 -15 -10  11 -20]
 [ 43 -29  19  -6 -11]
 [-20 -10   5   7 -32]]

 out of strock
[[ 2 37  0  0  0]
 [ 0  0  0 49 28]
 [54  0  0 11  0]
 [43  0 19  0  0]
 [ 0  0  5  7  0]]

 total sortage
[2 4 3 2 4]

 products with zero stock
[0 0 0 0 0]

 sort each row based on remaining stock
[[ 0  0  0  2 37]
 [ 0  0  0 28 49]
 [ 0  0  0 11 54]
 [ 0  0  0 19 43]
 [ 0  0  0  5  7]]


PANDA

In [ ]:
import pandas as pd